---
config:
  port: 2121
  buffer_size: 1024
tasks:
  - client: "192.168.7.1"
    server: "192.168.7.3"
    substitutions:
      - target: "README"
        sub: "main.rs"
      - target: "test.txt"
        sub: "evil_test.txt"
  - client: "192.168.7.2"
    server: "192.168.8.2"
    substitutions:
      - target: "README"
        sub: "main.rs"
      - target: "test.txt"
        sub: "evil_test.txt"
  - client: "127.0.0.1"
    server: "127.0.0.1"
    substitutions:
      - target: "README"
        sub: "main.rs"
      - target: "test.txt"
        sub: "evil_test.txt"

