---
config:
  directory: "./"
  port: 2121
  buffer_size: 1024
tasks:
  - client: "127.0.0.1"
    server: "127.0.0.1"
    substitutions:
      - target: "README"
        sub: "main.rs"
  - client: "10.10.10.10"
    server: "ftp.server.local"
    substitutions:
      - target: "dog.jpg"
        sub: "cat.jpg"
      - target: "main.cpp"
        sub: "main.rs"
  - client: "10.10.10.11"
    server: "ftp.server.local"
    substitutions:
      - target: "file.txt"
        sub: "file.jpg"